# https://hub.docker.com/r/google/dart
image: google/dart:2.8.4

variables:
  # Use to learn more:
  # pub run test --help
  PUB_VARS: "--platform vm --timeout 30s --concurrency=6 --test-randomize-ordering-seed=random --reporter=expanded"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .pub-cache/global_packages

before_script:
  - export PATH="$PATH":"~/.pub-cache/bin"
  - pub get --no-precompile

# test:
#   stage: test
#   script:
#     - pub run pwa

build:
  stage: build
  script:
    - pub global activate webdev
    - webdev build

development:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=postit-dev-ui --api-key=$HEROKU_API_KEY
  environment:
    name: Development
    url: https://postit-dev-ui.herokuapp.com/
  only:
    - master


staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=postit-staging-ui --api-key=$HEROKU_API_KEY
  environment:
    name: Staging
    url: https://postit-staging-ui.herokuapp.com/
  only:
    - master
  when: manual

production:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=postit-prod-ui --api-key=$HEROKU_API_KEY
  environment:
    name: Production
    url: https://postit-prod-ui.herokuapp.com/
  only:
    - master
  when: manual
