name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_forms: ^3.0.0
  angular_router: ^2.0.0-alpha+24
  http: ^0.12.0
  stream_transform: ^0.0.19
  angular_components: ^1.0.1
  emojis: ^0.9.3
  archive: ^2.0.13
  angular_modern_charts: ^0.2.0
  facebook_web_sdk: ^0.0.9
  # essential_components: ^1.9.18
  shelf: ^0.7.9
  http_server: ^0.9.8+3

dev_dependencies:
  angular_test: ^2.3.1
  build_runner: ^1.5.1
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  test: ^1.6.4
  sass_builder: ^2.0.0